using VolleyballCompetitionApp.Business.DTOs;
using VolleyballCompetitionApp.Business.RepositoryInterfaces;

namespace VolleyballCompetitionApp.Repository
{
	public class TeamRepository : ITeamRepository
	{
		private readonly string _connectionString;

		public TeamRepository(string connectionString) => _connectionString = connectionString;
		
		public int Create(int clubId, string name) // returns an int because the integer will be auto generated by the database so when you create the row you will be able to know what the id is
		{// the dto parameter shouldnt have a id yet (aka default int value) because the database will decide what the value will be
		 // database connection and data uploading 

			// no error's? return auto generated id (int)
			return 1;
		}
		// possible issue which could arise and need to be take care of 

		#region Find Methods

		public TeamDTO FindById(int id) // gets data from the database depending on the id
		{
			TeamDTO output = new TeamDTO { };
			// data base connection and data fetching

			// database connection and data fetching

			// no error's? return filled dto.
			return output;
		}

		public List<TeamDTO> FindByClubId(int clubId) // gets data from the database depending on the id
		{
			List<TeamDTO> output = new List<TeamDTO>();
			// data base connection and data fetching

			// database connection and data fetching

			// no error's? return filled dto.
			return output;
		}

		#endregion

		public void Update(int id, int clubId, string name) // uses dto.id to dicate to what row it alters then alters that row
		{
			// dto validation (does it have all variable's filled etc?)

			// database connection and data uploading/dating
		}

		public void Delete(int id)
		{
			// database connection and data deletion
		}
	}
}
